# For more info on HTTP files go to https://aka.ms/vs/httpfile
@URL = https://localhost:44354

### Get all projects
GET {{URL}}/api/projects 
accept: application/json

### Get project by id
GET {{URL}}/api/projects/1
accept: application/json

### Create project
POST {{URL}}/api/projects
Content-Type: application/json
{
  "title": "Valet app",
  "description": "A hub for parking your cars",
  "category": "Mobile",
  "status": "Ongoing"
}

### Update Project
PUT {{URL}}/api/projects/2
Content-Type: application/json
{
  "title": "Magazine",
  "description": "A documentation of all my personal projects",
  "category": "Web",
  "status": "Ongoing"
}

### Delete Project
DELETE {{URL}}/api/projects/4
Accept: application/json

### Get all projects with category
GET {{URL}}/api/projects?category=Web
accept: application/json

### Get all projects with status
GET {{URL}}/api/projects?status=Planned
accept: application/json
