# For more info on HTTP files go to https://aka.ms/vs/httpfile
@URL = https://localhost:7055

### Get all projects
GET {{URL}}/api/projects 
accept: application/json

### Get project by id
GET {{URL}}/api/projects/1
accept: application/json

### Create project
POST {{URL}}/api/projects
Content-Type: application/json
{
  "title": "Budget app",
  "description": "A hub for all users to manage their money",
  "category": "Mobile",
  "status": "Planned"
}

### Update Project
PUT {{URL}}/api/projects/2
Content-Type: application/json
{
  "title": "Magazine",
  "description": "A documentation of all my personal projects",
  "category": "Web",
  "status": "Ongoing"
}

### Delete Project
DELETE {{URL}}/api/projects/4
Accept: application/json