# For more info on HTTP files go to https://aka.ms/vs/httpfile
@URL = https://localhost:7055

### Get all technologies versions
GET {{URL}}/technologies/versions/all
accept: application/json

### Create technology version
POST {{URL}}/technologies/1/version
Content-Type: application/json
{
  "major": 0,
  "minor": 1,
  "patch": 0
}

### Get all project versions
GET {{URL}}/projects/versions/all
accept: application/json

### Create project version
POST {{URL}}/projects/1/version
Content-Type: application/json
{
  "major": 0,
  "minor": 1,
  "patch": 0
}