# For more info on HTTP files go to https://aka.ms/vs/httpfile
@URL = https://localhost:7055

### Get all technologies versions
GET {{URL}}/technologies/versions/all
accept: application/json

### Get all versions by for a technology
GET {{URL}}/technologies/1/versions
accept: application/json

### Create technology version
POST {{URL}}/technologies/1/versions
Content-Type: application/json
{
  "major": 0,
  "minor": 1,
  "patch": 0
}

### Delete technology version
DELETE {{URL}}/technologies/1/versions/3
accept: application/json
 
### Get all project versions
GET {{URL}}/projects/versions/all
accept: application/json

### Get all versions by for a project
GET {{URL}}/projects/1/versions
accept: application/json

### Create project version
POST {{URL}}/projects/1/versions
Content-Type: application/json
{
  "major": 0,
  "minor": 1,
  "patch": 0
}

### Delete project version
DELETE {{URL}}/projects/1/versions/2
accept: application/json