// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Infrastructure.Data;

#nullable disable

namespace Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260506221723_Update_relationships")]
    partial class Update_relationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Entities.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Projects.ProjectVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectVersion", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Technologies.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technology", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Technologies.TechnologyVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyId");

                    b.ToTable("TechnologyVersion", (string)null);
                });

            modelBuilder.Entity("ProjectVersionTechnology", b =>
                {
                    b.Property<int>("ProjectVersionId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyVersionId")
                        .HasColumnType("int");

                    b.HasKey("ProjectVersionId", "TechnologyVersionId");

                    b.HasIndex("TechnologyVersionId");

                    b.ToTable("ProjectVersionTechnology");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Projects.ProjectVersion", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Projects.Project", "Project")
                        .WithMany("ProjectVersions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Portfolio.Domain.ValueObjects.SemanticVersion", "Version", b1 =>
                        {
                            b1.Property<int>("ProjectVersionId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.Property<int>("Patch")
                                .HasColumnType("int");

                            b1.HasKey("ProjectVersionId");

                            b1.ToTable("ProjectVersion");

                            b1.WithOwner()
                                .HasForeignKey("ProjectVersionId");
                        });

                    b.Navigation("Project");

                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Technologies.TechnologyVersion", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Technologies.Technology", "Technology")
                        .WithMany("Versions")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Portfolio.Domain.ValueObjects.SemanticVersion", "Version", b1 =>
                        {
                            b1.Property<int>("TechnologyVersionId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.Property<int>("Patch")
                                .HasColumnType("int");

                            b1.HasKey("TechnologyVersionId");

                            b1.ToTable("TechnologyVersion");

                            b1.WithOwner()
                                .HasForeignKey("TechnologyVersionId");
                        });

                    b.Navigation("Technology");

                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectVersionTechnology", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Projects.ProjectVersion", null)
                        .WithMany()
                        .HasForeignKey("ProjectVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.Technologies.TechnologyVersion", null)
                        .WithMany()
                        .HasForeignKey("TechnologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Projects.Project", b =>
                {
                    b.Navigation("ProjectVersions");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Technologies.Technology", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
