# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - cm-portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore src/Portfolio.API/Portfolio.API.csproj

      - name: Build
        run: dotnet build src/Portfolio.API/Portfolio.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/Portfolio.API/Portfolio.API.csproj -c Release -o myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout (needed for EF CLI)
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: myapp

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef --version 9.*

      - name: Add .NET tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get connection string from Azure
        id: get_conn
        run: |
          $conn = az webapp config connection-string list `
            --name cm-portfolio `
            --resource-group APIs `
            --query "[?name=='PortfolioDB'].connectionString" `
            -o tsv

          echo "DB_CONNECTION_STRING=$conn" >> $env:GITHUB_ENV

      - name: Run EF Core migrations
        run: dotnet ef database update --project src/Portfolio.Infrastructure --startup-project src/Portfolio.API --connection "$env:DB_CONNECTION_STRING"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: cm-portfolio
          slot-name: Production
          package: myapp